streams.native:
	ocamlbuild -classic-display -use-ocamlfind streams.native

streams.byte:
	ocamlbuild -classic-display -use-ocamlfind streams.byte

clean:
	rm -rf _build *.native *.byte

.PHONY: streams.native streams.byte
